# Generated by Django 4.2.3 on 2023-07-08 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Papers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_id', models.CharField(max_length=100)),
                ('question_text', models.TextField()),
                ('options', models.CharField(max_length=100)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('year_of_study', models.IntegerField()),
                ('unit', models.CharField(max_length=100)),
                ('question_type', models.CharField(max_length=100)),
            ],
        ),
    ]
