# Generated by Django 4.2.3 on 2023-07-15 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('papers', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Level',
            new_name='LevelOfStudy',
        ),
        migrations.RemoveField(
            model_name='shortanswerquestion',
            name='paper',
        ),
        migrations.RemoveField(
            model_name='shortanswerquestion',
            name='topic',
        ),
        migrations.RenameField(
            model_name='unit',
            old_name='level',
            new_name='level_of_study',
        ),
        migrations.AlterField(
            model_name='multiplechoicequestion',
            name='multiple_choice_question_text',
            field=models.CharField(max_length=200),
        ),
        migrations.DeleteModel(
            name='Attempt',
        ),
        migrations.DeleteModel(
            name='ShortAnswerQuestion',
        ),
    ]
