# Generated by Django 4.2.3 on 2023-07-10 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('papers', '0003_rename_question_id_paper_title_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='question_id',
        ),
        migrations.AlterField(
            model_name='paper',
            name='options',
            field=models.JSONField(max_length=100),
        ),
    ]
