# Generated by Django 4.2.3 on 2023-07-10 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('papers', '0004_remove_question_question_id_alter_paper_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paper',
            name='options',
            field=models.CharField(max_length=100),
        ),
    ]
