# Generated by Django 4.2.3 on 2023-07-10 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('papers', '0005_alter_paper_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paper',
            name='options',
        ),
    ]
